#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecLight.Output
{
    
    #line 9 "..\..\Output\SinglePageRazorTemplate.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Output\SinglePageRazorTemplate.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Output\SinglePageRazorTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 12 "..\..\Output\SinglePageRazorTemplate.cshtml"
    using SpecLight;
    
    #line default
    #line hidden
    
    #line 13 "..\..\Output\SinglePageRazorTemplate.cshtml"
    using SpecLight.Infrastructure;
    
    #line default
    #line hidden
    
    #line 14 "..\..\Output\SinglePageRazorTemplate.cshtml"
    using SpecLight.Output.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class SinglePageRazorTemplate : SpecLight.Output.RazorTemplateBase
    {
#line hidden
#line hidden
public System.Web.WebPages.HelperResult RenderMarkdown(string s)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 154 "..\..\Output\SinglePageRazorTemplate.cshtml"
 
	var html = Markdown.Instance.Transform(s);
	
#line default
#line hidden


#line 156 "..\..\Output\SinglePageRazorTemplate.cshtml"
WriteTo(@__razor_helper_writer, RawHtml(html));

#line default
#line hidden


#line 156 "..\..\Output\SinglePageRazorTemplate.cshtml"
               

#line default
#line hidden

});

}

#line hidden
public System.Web.WebPages.HelperResult TagBox(IEnumerable<string> tags)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 160 "..\..\Output\SinglePageRazorTemplate.cshtml"
 
	if (tags == null || !tags.Any())
	{
		return;
	}

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t<span class=\"tags\">");



#line 165 "..\..\Output\SinglePageRazorTemplate.cshtml"
WriteTo(@__razor_helper_writer, string.Join(", ", tags.Select(x => "@" + x)));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 166 "..\..\Output\SinglePageRazorTemplate.cshtml"

#line default
#line hidden

});

}

#line hidden
public System.Web.WebPages.HelperResult ExtraData(IDictionary<string, object> dataDictionary)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 169 "..\..\Output\SinglePageRazorTemplate.cshtml"
 
	var data = dataDictionary.FormatExtraData();
	if (!string.IsNullOrWhiteSpace(data))
	{

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t\t<span class=\"extra-data\" title=\"Extra Data\">");



#line 173 "..\..\Output\SinglePageRazorTemplate.cshtml"
               WriteTo(@__razor_helper_writer, data);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 174 "..\..\Output\SinglePageRazorTemplate.cshtml"
	}

#line default
#line hidden

});

}

#line hidden
public System.Web.WebPages.HelperResult FolderToc(FolderViewModel folder)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 178 "..\..\Output\SinglePageRazorTemplate.cshtml"
 
	if (!string.IsNullOrWhiteSpace(folder.Name))
	{
		var statusCounts = folder.DescendantClasses().SelectMany(y => y.Specs.Select(x => x.Status)).ToList();

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t\t<span class=\"folderName\">\r\n\t\t\t<span class=\"folderGlyph\"></span>\r\n\t\t\t<span class" +
"=\"folderNameText\">");



#line 184 "..\..\Output\SinglePageRazorTemplate.cshtml"
 WriteTo(@__razor_helper_writer, folder.Name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</span>\r\n\t\t\t<span class=\"graph\" style=\"");



#line 185 "..\..\Output\SinglePageRazorTemplate.cshtml"
WriteTo(@__razor_helper_writer, Gradient(statusCounts));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" title=\"");



#line 185 "..\..\Output\SinglePageRazorTemplate.cshtml"
                               WriteTo(@__razor_helper_writer, Title(statusCounts));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " in folder \'");



#line 185 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                               WriteTo(@__razor_helper_writer, folder.Name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\'\"></span>\r\n\t\t</span>\r\n");



#line 187 "..\..\Output\SinglePageRazorTemplate.cshtml"
	}

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t<ul data-tags=\"");



#line 188 "..\..\Output\SinglePageRazorTemplate.cshtml"
WriteTo(@__razor_helper_writer, string.Join(" ", folder.DescendantClasses().SelectMany(x => x.Specs).SelectMany(x => x.EffectiveTags()).Distinct()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 189 "..\..\Output\SinglePageRazorTemplate.cshtml"
 		foreach (var child in folder.SubFolders.OrderBy(x => x.Name))
		{
			var featureClass = folder.DescendantClasses().SelectMany(x => x.Specs).Select(x => x.Status).DefaultIfEmpty(Status.Pending).Max().ToString().ToLowerInvariant();

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t\t\t<li class=\"folder ");



#line 192 "..\..\Output\SinglePageRazorTemplate.cshtml"
WriteTo(@__razor_helper_writer, featureClass);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n\r\n\t\t\t\t");



#line 194 "..\..\Output\SinglePageRazorTemplate.cshtml"
WriteTo(@__razor_helper_writer, FolderToc(child));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n\t\t\t</li>\r\n");



#line 196 "..\..\Output\SinglePageRazorTemplate.cshtml"
		}

#line default
#line hidden



#line 197 "..\..\Output\SinglePageRazorTemplate.cshtml"
 		foreach (var feature in folder.Classes.OrderBy(x => x.Name))
		{
			var maxStatus = feature.Specs.Select(x => x.Status).DefaultIfEmpty(Status.Pending).Max();
			var featureClass = maxStatus.ToString().ToLowerInvariant();

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t\t\t<li class=\"feature ");



#line 201 "..\..\Output\SinglePageRazorTemplate.cshtml"
WriteTo(@__razor_helper_writer, featureClass);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" title=\"Feature: ");



#line 201 "..\..\Output\SinglePageRazorTemplate.cshtml"
                      WriteTo(@__razor_helper_writer, feature.Name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " (");



#line 201 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                     WriteTo(@__razor_helper_writer, maxStatus);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ")\" data-tags=\"");



#line 201 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                             WriteTo(@__razor_helper_writer, string.Join(" ", feature.Specs.SelectMany(x => x.EffectiveTags()).Distinct()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n\t\t\t\t<a class=\"featureLink\" href=\"#");



#line 202 "..\..\Output\SinglePageRazorTemplate.cshtml"
   WriteTo(@__razor_helper_writer, AnchorName(feature));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 202 "..\..\Output\SinglePageRazorTemplate.cshtml"
                         WriteTo(@__razor_helper_writer, feature.Name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a>\r\n\t\t\t\t<ul class=\"scenarios\">\r\n");



#line 204 "..\..\Output\SinglePageRazorTemplate.cshtml"
 					foreach (var spec in feature.Specs)
					{
						var scenarioClass = spec.Status.ToString().ToLowerInvariant();

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t\t\t\t\t\t<li class=\"");



#line 207 "..\..\Output\SinglePageRazorTemplate.cshtml"
WriteTo(@__razor_helper_writer, scenarioClass);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" title=\"Scenario: ");



#line 207 "..\..\Output\SinglePageRazorTemplate.cshtml"
                   WriteTo(@__razor_helper_writer, spec.MethodName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " (");



#line 207 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                     WriteTo(@__razor_helper_writer, spec.Status);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ")\" data-tags=\"");



#line 207 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                               WriteTo(@__razor_helper_writer, string.Join(" ", spec.EffectiveTags()));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n\t\t\t\t\t\t\t<a class=\"scenarioLink\" href=\"#");



#line 208 "..\..\Output\SinglePageRazorTemplate.cshtml"
       WriteTo(@__razor_helper_writer, AnchorName(feature, spec));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 208 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                   WriteTo(@__razor_helper_writer, spec.MethodName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a>\r\n\t\t\t\t\t\t</li>\r\n");



#line 210 "..\..\Output\SinglePageRazorTemplate.cshtml"
					}

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t\t\t\t</ul>\r\n\t\t\t</li>\r\n");



#line 213 "..\..\Output\SinglePageRazorTemplate.cshtml"
		}

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t</ul>\r\n");



#line 215 "..\..\Output\SinglePageRazorTemplate.cshtml"

#line default
#line hidden

});

}


        #line 218 "..\..\Output\SinglePageRazorTemplate.cshtml"


	string AnchorName(TestClassViewModel c, SpecViewModel spec)
	{
		return "Scenario-" + (c.Namespace + "." + c.Name + "-" + spec.MethodName).Replace(" ", "_");
	}

	string AnchorName(TestClassViewModel c)
	{
		return "Feature-" + (c.Namespace + "." + c.Name).Replace(" ", "_");
	}


	static readonly Dictionary<Status, string> StatusColours = new Dictionary<Status, string>
    {
        {Status.Passed, "rgba(86, 158, 78, 0.9)"},
        {Status.Failed, "rgba(238, 66, 68, 0.9)"},
        {Status.Skipped, "rgba(245, 184, 81, 0.9)"},
        {Status.Pending, "rgba(245, 220, 95, 0.9)"},
        {Status.NotRun, "transparent"},
    };

	static readonly Status[] HumanOrderedStatuses = { Status.Failed, Status.Passed, Status.Skipped, Status.Pending, Status.NotRun };

	static string Gradient(IEnumerable<Status> statuses)
	{
		double tp = 0;
		var s = "";
		foreach (var status in HumanOrderedStatuses)
		{
			var colour = StatusColours[status];
			s += string.Format(", {0} {1}%", colour, tp);
			tp += statuses.Count(y => y == status) / (double)statuses.Count() * 100;
			s += string.Format(", {0} {1}%", colour, tp);
		}


		return "background-image: linear-gradient(to right" + s + ")";
	}


	static string Title(IEnumerable<Status> statuses)
	{
		var v = from s in HumanOrderedStatuses
				let count = statuses.Count(y => y == s)
				where count > 0
				select count + " " + s;

		return string.Join(", ", v);
	}


        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n");









            
            #line 16 "..\..\Output\SinglePageRazorTemplate.cshtml"
  
	var statusCounts = TemplateModel.RootFolder.DescendantClasses().SelectMany(y => y.Specs.Select(x => x.Status));
	var tags = TemplateModel.Tags.ToList();
	double fattestTagCount = tags.Select(x => x.Statuses.Count()).DefaultIfEmpty(1).Max();


            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n\t" +
"<meta charset=\"utf-8\" />\r\n\t<title>SpecLight report</title>\r\n\t<style type=\"text/c" +
"ss\">\r\n\t\t\t");


            
            #line 27 "..\..\Output\SinglePageRazorTemplate.cshtml"
Write(IncludeEmbeddedResource("Style.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</style>\r\n\t<script type=\"text/javascript\">\r\n\t    ");


            
            #line 30 "..\..\Output\SinglePageRazorTemplate.cshtml"
Write(IncludeEmbeddedResource("jquery-1.10.2.min.js"));

            
            #line default
            #line hidden
WriteLiteral(@"
	</script>



	<script type=""text/javascript"">
	    $(function () {
	        //folder collapsing
	        $(""li.folder > span.folderName"").click(function () {
	            $(this).parent().toggleClass(""collapsed"");
	        });

	        //highlight current item
	        function updateHighlight() {
	            $(""#TableOfContents a"").removeClass(""current"");
	            $(""h2[id], h3[id]"").filter("":visible"").filter(function () {
	                var elemTop = $(this).offset().top;
	                return elemTop >= 0;
	            }).first().each(function () {
	                $(""#TableOfContents a[href='#"" + this.id + ""']"").addClass(""current"");
	            });
	        }

	        $(""#Content"").scroll(updateHighlight);
	        updateHighlight();

	        //tag behaviour
	        $(""input[data-tag-controller]"").change(function () {
	            var selectedTags = $(""input[data-tag-controller]:checked"").map(function (i, d) { return $(d).data(""tag-controller""); });
	            if (selectedTags.size()) {
	                $(""*[data-tags]"").hide();
	                selectedTags.each(function () { $(""*[data-tags~='"" + this + ""']"").show(); });
	            } else {
	                $(""*[data-tags]"").show();
	            }
	            updateHighlight();
	        });
	    });
	</script>
</head>
<body>
	<div id=""TableOfContents"">
		<div class=""graph"" style=""");


            
            #line 72 "..\..\Output\SinglePageRazorTemplate.cshtml"
                       Write(Gradient(statusCounts));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Status breakdown for all scenarios\">");


            
            #line 72 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                                                           Write(Title(statusCounts));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\t\t<div class=\"tagCloud\">\r\n");


            
            #line 74 "..\..\Output\SinglePageRazorTemplate.cshtml"
 			foreach (var tag in tags)
			{
				var fatness = (tag.Statuses.Count() - 1) / fattestTagCount;
				var size = 90 + fatness * 60;


            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<input id=\"tagCheckbox-");


            
            #line 79 "..\..\Output\SinglePageRazorTemplate.cshtml"
                      Write(tag.Name);

            
            #line default
            #line hidden
WriteLiteral("\" type=\"checkbox\" data-tag-controller=\"");


            
            #line 79 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                                      Write(tag.Name);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");



WriteLiteral("\t\t\t\t<label for=\"tagCheckbox-");


            
            #line 80 "..\..\Output\SinglePageRazorTemplate.cshtml"
                       Write(tag.Name);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Tag \'");


            
            #line 80 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                              Write(tag.Name);

            
            #line default
            #line hidden
WriteLiteral("\' (");


            
            #line 80 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                          Write(Title(tag.Statuses));

            
            #line default
            #line hidden
WriteLiteral(") - Click to filter\" style=\"");


            
            #line 80 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                                                                          Write(Gradient(tag.Statuses));

            
            #line default
            #line hidden
WriteLiteral("; font-size: ");


            
            #line 80 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                                                                                                               Write(size);

            
            #line default
            #line hidden
WriteLiteral("%\">");


WriteLiteral("@");


            
            #line 80 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                                                                                                                          Write(tag.Name);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");


            
            #line 81 "..\..\Output\SinglePageRazorTemplate.cshtml"
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t</div>\r\n\t\t");


            
            #line 83 "..\..\Output\SinglePageRazorTemplate.cshtml"
Write(FolderToc(TemplateModel.RootFolder));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\t</div>\r\n\t<div id=\"Content\">\r\n\t\t<h1>Speclight report</h1>\r\n\r\n");


            
            #line 89 "..\..\Output\SinglePageRazorTemplate.cshtml"
 		foreach (var testClass in TemplateModel.RootFolder.DescendantClasses())
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<div class=\"feature\" data-tags=\"");


            
            #line 91 "..\..\Output\SinglePageRazorTemplate.cshtml"
                              Write(string.Join(" ", testClass.Specs.SelectMany(x => x.EffectiveTags()).Distinct()));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t<h2 id=\"");


            
            #line 92 "..\..\Output\SinglePageRazorTemplate.cshtml"
       Write(AnchorName(testClass));

            
            #line default
            #line hidden
WriteLiteral("\">Class: ");


            
            #line 92 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                      Write(testClass.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\t\t\t\t");


            
            #line 93 "..\..\Output\SinglePageRazorTemplate.cshtml"
Write(TagBox(testClass.Specs.SelectMany(x => x.EffectiveTags()).Distinct()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 94 "..\..\Output\SinglePageRazorTemplate.cshtml"
 				if (testClass.Description != null)
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<div class=\"class-description markdown-host\">\r\n\t\t\t\t\t\t");


            
            #line 97 "..\..\Output\SinglePageRazorTemplate.cshtml"
 Write(RenderMarkdown(testClass.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n");


            
            #line 99 "..\..\Output\SinglePageRazorTemplate.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 101 "..\..\Output\SinglePageRazorTemplate.cshtml"
 				foreach (var spec in testClass.Specs)
				{
					var firstError = spec.Spec.Outcomes.Select(x => x.Error).FirstOrDefault(x => x != null);

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<div class=\"scenario ");


            
            #line 104 "..\..\Output\SinglePageRazorTemplate.cshtml"
                     Write(spec.Status.ToString().ToLowerInvariant());

            
            #line default
            #line hidden
WriteLiteral("\" data-tags=\"");


            
            #line 104 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                                            Write(string.Join(" ", spec.EffectiveTags()));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t\t\t<h3 id=\"");


            
            #line 105 "..\..\Output\SinglePageRazorTemplate.cshtml"
         Write(AnchorName(testClass, spec));

            
            #line default
            #line hidden
WriteLiteral("\">Method: ");


            
            #line 105 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                               Write(spec.MethodName);

            
            #line default
            #line hidden
WriteLiteral("  (");


            
            #line 105 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                                  Write(spec.Status.ToString());

            
            #line default
            #line hidden
WriteLiteral(")</h3>\r\n\t\t\t\t\t\t");


            
            #line 106 "..\..\Output\SinglePageRazorTemplate.cshtml"
 Write(TagBox(spec.Spec.SpecTags));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t<p class=\"description markdown-host\">");


            
            #line 107 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                      Write(RenderMarkdown(spec.Spec.Description));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\t\t\t\t\t\t");


            
            #line 108 "..\..\Output\SinglePageRazorTemplate.cshtml"
 Write(ExtraData(spec.Spec.DataDictionary));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t<ul>\r\n");


            
            #line 110 "..\..\Output\SinglePageRazorTemplate.cshtml"
 							foreach (var o in spec.Spec.Outcomes)
							{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t<li class=\"");


            
            #line 112 "..\..\Output\SinglePageRazorTemplate.cshtml"
              Write(o.Status.ToString().ToLowerInvariant());

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 112 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                       Write(o.Empty?"empty":"");

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 112 "..\..\Output\SinglePageRazorTemplate.cshtml"
                                                                                    Write(o.Error);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t\t\t\t\t\t<em>");


            
            #line 113 "..\..\Output\SinglePageRazorTemplate.cshtml"
        Write(o.Step.Type);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n\t\t\t\t\t\t\t\t\t");


            
            #line 114 "..\..\Output\SinglePageRazorTemplate.cshtml"
    Write(o.Step.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 115 "..\..\Output\SinglePageRazorTemplate.cshtml"
 									if (o.Empty)
									{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t\t<strong title=\"Test step contained no code\">(Empty)</strong>\r\n");


            
            #line 118 "..\..\Output\SinglePageRazorTemplate.cshtml"
									}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t");


            
            #line 119 "..\..\Output\SinglePageRazorTemplate.cshtml"
    Write(TagBox(o.Step.Tags));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t");


            
            #line 120 "..\..\Output\SinglePageRazorTemplate.cshtml"
    Write(ExtraData(o.Step.DataDictionary));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t</li>\r\n");


            
            #line 122 "..\..\Output\SinglePageRazorTemplate.cshtml"
							}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t</ul>\r\n");


            
            #line 124 "..\..\Output\SinglePageRazorTemplate.cshtml"
 						if (firstError != null)
						{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t<pre class=\"errorMessage\">");


            
            #line 126 "..\..\Output\SinglePageRazorTemplate.cshtml"
                            Write(firstError);

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n");


            
            #line 127 "..\..\Output\SinglePageRazorTemplate.cshtml"
						}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t</div>\r\n");


            
            #line 129 "..\..\Output\SinglePageRazorTemplate.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</div>\r\n");


            
            #line 131 "..\..\Output\SinglePageRazorTemplate.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t<div id=\"environment\">\r\n\t\t\t<ul>\r\n\t\t\t\t<li><b>Generated At: </b>");


            
            #line 135 "..\..\Output\SinglePageRazorTemplate.cshtml"
                        Write(DateTime.Now.ToString());

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");


            
            #line 136 "..\..\Output\SinglePageRazorTemplate.cshtml"
 				foreach (string key in Environment.GetEnvironmentVariables().Keys
					.Cast<string>()
					.Where(x => x.StartsWith("build", StringComparison.OrdinalIgnoreCase)))
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<li>\r\n\t\t\t\t\t\t<b>");


            
            #line 141 "..\..\Output\SinglePageRazorTemplate.cshtml"
    Write(key);

            
            #line default
            #line hidden
WriteLiteral(": </b>\r\n\t\t\t\t\t\t");


            
            #line 142 "..\..\Output\SinglePageRazorTemplate.cshtml"
 Write(Environment.GetEnvironmentVariable(key));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</li>\r\n");


            
            #line 144 "..\..\Output\SinglePageRazorTemplate.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</ul>\r\n\r\n\t\t</div>\r\n\r\n\t</div>\r\n</body>\r\n</html>\r\n\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
